apiVersion: v1
kind: Pod
metadata:
  name: getting-started-pod
spec:
  containers:
  - name: getting-started
    image: shirokumasoftware/getting-started:latest
    command: ["/bin/sh", "-c"]
    args: ["echo -n 'Hello Persistent Volume' > /share/hello.txt && ./app"]
    ports:
    - containerPort: 8000
    imagePullPolicy: Always
    volumeMounts:
    - name: pvc-volume
      mountPath: "/share"
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: nfs-pvc