apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-app
        image: shirokumasoftware/example-auth-app:latest
        ports:
          - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
  selector:
    app: auth-app