apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rbac-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rbac-api
    spec:
      serviceAccountName: rbac-api
      containers:
      - name: rbac-api
        image: shirokumasoftware/example-rbac:latest
        ports:
          - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rbac-api
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30011
    protocol: TCP
  selector:
    app: rbac-api